In [1]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import re

In [9]:
Myarray= ['C:/Users/fobus/Desktop/GIT_TEST/nltk/HomeWork2/The Hobbit 1937.txt','C:/Users/fobus/Desktop/GIT_TEST/nltk/HomeWork2/Two Towers 1954.txt', 
    'C:/Users/fobus/Desktop/GIT_TEST/nltk/HomeWork2/The Fellowship of the Ring 1954.txt','C:/Users/fobus/Desktop/GIT_TEST/nltk/HomeWork2/THE ADVENTURES OF TOM BOMBADIL 1967.txt', 
    'C:/Users/fobus/Desktop/GIT_TEST/nltk/HomeWork2/The Silmarillion 1977.txt','C:/Users/fobus/Desktop/GIT_TEST/nltk/HomeWork2/The Children 2007.txt'] 

In [10]:

class TextProcessor:
    def __init__(self, texts):
        self.texts = texts
        self.processed_texts = self.preprocess_texts()

    def preprocess_texts(self):
        processed_texts = []
        for text in self.texts:
            text = text.lower()
            text = re.sub(r'[^a-zA-Z ]', '', text)
            processed_texts.append(text)
        return processed_texts

    def calculate_cosine_similarity(self):
        vectorizer = TfidfVectorizer()
        tfidf_matrix = vectorizer.fit_transform(self.processed_texts)
        similarity_matrix = cosine_similarity(tfidf_matrix, tfidf_matrix)
        return similarity_matrix
 
texts = Myarray

text_processor = TextProcessor(texts)
similarity_matrix = text_processor.calculate_cosine_similarity()

print("Матрица косинусного сходства между текстами:")
print(similarity_matrix)

Матрица косинусного сходства между текстами:
[[1.         0.11003822 0.18712256 0.18712256 0.31484573 0.31484573]
 [0.11003822 1.         0.06539912 0.06539912 0.11003822 0.11003822]
 [0.18712256 0.06539912 1.         0.27395034 0.18712256 0.18712256]
 [0.18712256 0.06539912 0.27395034 1.         0.18712256 0.18712256]
 [0.31484573 0.11003822 0.18712256 0.18712256 1.         0.31484573]
 [0.31484573 0.11003822 0.18712256 0.18712256 0.31484573 1.        ]]
