In [33]:
%pip install numpy 
import numpy as np 
np.matrix 


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


numpy.matrix

In [37]:

class Matrix:
    def __init__(self, matrix):
        self.matrix = matrix
# находим кооличество строк в матрице 
    def rows_matrix(self): 
        rows = len(self.matrix)  
        return rows 
# Находим колличество столбцов в матрице 
    def cols_matrix(self): 
        cols = len(self.matrix[0])  
        return cols   
# Сложение------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
    # Матрица и число 
    def __add__(self,Matrix_or_number): 
        # Проверка является ли переменая Matrix_or_numbera числом 
        if isinstance(Matrix_or_number, int) or isinstance(Matrix_or_number, float):
            result = [] 
            # Итерация по строчке
            for row in self.matrix:
                new_row = [] 
                # Итерация по элементам строки 
                for element in row:
                    new_element = element + Matrix_or_number 
                    # Добовляем новый элемент в конец списка 
                    new_row.append(new_element) 
                    # тут тоже самое , важная пометка - вложеный цикл я использовал что бы пройтись по всем элементам матрицы (self.matrix)
                result.append(new_row)
            return Matrix(result) 
        # Матрица и матрица 
        # Собственно проверка на число получает folse , поэтому выполняется эта часть код 
        else: 
            result = []
            for i in range(self.rows_matrix()):
                row = []
                for j in range(self.cols_matrix()):
                    sum_ij = self.matrix[i][j] + Matrix_or_number.matrix[i][j] 
                    row.append(sum_ij) 
                result.append(row)
            return Matrix(result)   
        # Этот код с минимальными изменениями используется на 8 тестах , поэтому в будущем не буду их комитить 
        
# Вычитание-------------------------------------------------------------------------------------------------------------------------------------------------------------------
    # Матрица и число 
    def __sub__(self,Matrix_or_number):
        if isinstance(Matrix_or_number, int) or isinstance(Matrix_or_number, float):
            result = []
            for row in self.matrix:
                new_row = []
                for element in row:
                    new_element = element - Matrix_or_number
                    new_row.append(new_element)
                result.append(new_row)
            return Matrix(result) 
        # Матрица и матрица
        else: 
            result = []
            for i in range(self.rows_matrix()):
                row = []
                for j in range(self.cols_matrix()):
                    sum_ij = self.matrix[i][j] - Matrix_or_number.matrix[i][j]
                    row.append(sum_ij)
                result.append(row)
            return Matrix(result) 
    # умножение --------------------------------------------------------------------------------------------------------------------------------------------------------------- 
      
    # матрицы и число
    def __mul__(self,Matrix_or_number):
        if isinstance(Matrix_or_number, int) or isinstance(Matrix_or_number, float):
            result = []
            for row in self.matrix:
                new_row = []
                for element in row:
                    new_element = element * Matrix_or_number
                    new_row.append(new_element)
                result.append(new_row)
            return Matrix(result) 
        # Матрица и матрица 

        else: 
            result = []
            for i in range(self.rows_matrix()):
                row = []
                for j in range(self.cols_matrix()):
                    sum_ij = self.matrix[i][j] * Matrix_or_number.matrix[i][j]
                    row.append(sum_ij)
                result.append(row)
            return Matrix(result)   
    # Деление ----------------------------------------------------------------------------------------------------------------------------------------- 
    # матрица и число 
    def __truediv__(self,Matrix_or_number):
        if isinstance(Matrix_or_number, int) or isinstance(Matrix_or_number, float): 
            result = []
            for row in self.matrix:
                new_row = []
                for element in row:
                    new_element = element / Matrix_or_number
                    new_row.append(new_element)
                result.append(new_row)
            return Matrix(result) 
        # Матрица и матрица 
        
        else: 
            result = []
            for i in range(self.rows_matrix()):
                row = []
                for j in range(self.cols_matrix()):
                    sum_ij = self.matrix[i][j] / Matrix_or_number.matrix[i][j]
                    row.append(sum_ij)
                result.append(row)
            return Matrix(result)   

    #Транспонирование -------------------------------------------------------------------------------------------------------------------------------------------------  
    # Последовал твоему совету и реализовал траспониронирование используя "Питоновский сахар" 
    def T(self): 
        # Буквально созадется список (двумерный /многомерный ) не уверен как называется , мы отдаетм ему элементы данной матрицы что бы случилось транспонирование [i][j]-[j][i]
        transposed = [[self.matrix[j][i] for j in range(self.rows_matrix())] for i in range(self.cols_matrix())]
        return Matrix(transposed)  
         
    #   скалярка ---------------------------------------------------------------------------------------------------------------------------------------------  
    def __matmul__(self,other_Matrix): 
        # проверяю размерность , совпадают ли они 
        if self.cols_matrix() != other_Matrix.rows_matrix():  
            #  Если размерности не совпадают, проверяем, можно ли выполнить транспонирование : 
            # сравниваем количество строк первой матрицы с количеством столбцов второй матрицы так же 
            # количество столбцов первой матрицы с количеством строк второй матрицы
            if self.rows_matrix() == other_Matrix.cols_matrix() and self.cols_matrix() == other_Matrix.rows_matrix(): 
                # принимаем тарнспонирование , использовал свою функцию , надеюсь ничего криминального 
                other_Matrix.matrix = self.T(other_Matrix.matrix) 
                # создаю пустую матрицу размер - кол-во строк первой натрицы на кол во кол- во столбцов второй матрицы 
        result = [[0] * other_Matrix.cols_matrix() for l in range(self.rows_matrix())]
                # идем по строкам 1 матрицы
        for i in range(self.rows_matrix()): 
            # идем по столбцам 2 матрицы
            for j in range(other_Matrix.cols_matrix()): 
                # идем по стобцу 1 .тк Для каждого элемента в строке первой матрицы и столбце второй матрицы мы будем выполнять  
                for k in range(self.cols_matrix()): 
                    # тут вычисляется скалярное произведение- строки первой матрицы и столбца второй матрицы после добовляю его к нужному элементу матрицы результата.
                    result[i][j] += self.matrix[i][k] * other_Matrix.matrix[k][j]

        return Matrix(result)

   

In [35]:
%pip install -q ipytest pytest

import ipytest
import pytest
ipytest.autoconfig()

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [36]:
%%ipytest
import numpy as np

matrix1 = Matrix([[1,2,3],[1,2,3],[1,2,3]])
matrix2 = Matrix([[4,5,6],[4,5,6],[4,5,6]]) 
matrix3 = Matrix([[4,5,6],[4,5,6],[4,5,6]])

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])
def test_matrix_add_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (np.array((matrix1 + matrix2).matrix) == (np.array(matrix1.matrix) + np.array(matrix2.matrix))).all()
    ), 'add section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 13.2]])
def test_matrix_add_number(matrix1: Matrix, number: int | float):
    assert (
        (np.array((matrix1 + number).matrix) == np.array(matrix1.matrix) + number).all()
    ), 'add section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])
def test_matrix_sub_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (np.array((matrix1 - matrix2).matrix) == np.array(matrix1.matrix) - np.array(matrix2.matrix)).all()
    ), 'sub section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 12.2]])    
def test_matrix_sub_number(matrix1: Matrix, number: int | float):
    assert (
        (np.array((matrix1 - number).matrix) == np.array(matrix1.matrix) - number).all()
    ), 'sub section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1", [matrix1])    
def test_matrix_transpose(matrix1: Matrix):
    assert (
        (np.array(matrix1.T().matrix) == np.array(matrix1.matrix).T).all()
    ), 'transpose section is not working right'
    
# -----------------------------------------

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])
def test_matrix_mul_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (np.array((matrix1 * matrix2).matrix) == np.array(matrix1.matrix) * np.array(matrix2.matrix)).all()
    ), 'mul section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 13]])
def test_matrix_mul_number(matrix1: Matrix, number: int | float):
    assert (
        (np.array((matrix1 * number).matrix) == np.array(matrix1.matrix) * number).all()
    ), 'mul section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])    
def test_matrix_div_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (np.array((matrix1 / matrix2).matrix) == np.array(matrix1.matrix) / np.array(matrix2.matrix)).all()
    ), 'div section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 2]])    
def test_matrix_div_number(matrix1: Matrix, number: int | float):
    assert (
        (np.array((matrix1 / number).matrix) == np.array(matrix1.matrix) / number).all()
    ), 'div section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2.T()]])    
def test_matrix_matmul_matrix(matrix1: Matrix, matrix2: Matrix):
    assert(
        (np.array((matrix1 @ matrix2).matrix) == np.array(matrix1.matrix) @ np.array(matrix2.matrix)).all()
    ), 'matmul section is not working right, and don\'t forget about T() if needed'

print((matrix1*matrix2).matrix)
print(np.array(matrix1.matrix) * np.array(matrix2.matrix))


[[4, 10, 18], [4, 10, 18], [4, 10, 18]]
[[ 4 10 18]
 [ 4 10 18]
 [ 4 10 18]]
.........F                                                                                   [100%]
============================================ FAILURES =============================================
__________________________ test_matrix_matmul_matrix[matrix10-matrix20] ___________________________

matrix1 = <__main__.Matrix object at 0x0000024BAF6C3AC0>
matrix2 = <__main__.Matrix object at 0x0000024BC0978820>

    @pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2.T()]])
    def test_matrix_matmul_matrix(matrix1: Matrix, matrix2: Matrix):
>       assert(
            (np.array((matrix1 @ matrix2).matrix) == np.array(matrix1.matrix) @ np.array(matrix2.matrix)).all()
        ), 'matmul section is not working right, and don\'t forget about T() if needed'

C:\Users\fobus\AppData\Local\Temp\ipykernel_13052\2152926690.py:65: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 